# Generated by Django 4.2.28 on 2026-02-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(choices=[('SOY', 'Soja'), ('CRN', 'Milho'), ('USD', 'Dólar')], max_length=3, verbose_name='Commodity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)')),
                ('date', models.DateField(verbose_name='Data da Cotação')),
                ('location', models.CharField(blank=True, help_text='Ex: Toledo, Cascavel (Deixe em branco para cotações gerais como o Dólar)', max_length=100, null=True, verbose_name='Localização')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
            ],
            options={
                'verbose_name': 'Cotação',
                'verbose_name_plural': 'Cotações',
                'ordering': ['-date', 'commodity'],
            },
        ),
    ]
