# Generated by Django 4.2.29 on 2026-03-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(choices=[('SOY', 'Soja'), ('CRN', 'Milho'), ('WHT', 'Trigo')], max_length=3, verbose_name='Cultura')),
                ('date', models.DateField(verbose_name='Data da Cotação')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)')),
                ('source', models.CharField(default='Sindicato Rural de Toledo', max_length=100, verbose_name='Fonte dos Dados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cotação de Mercado',
                'verbose_name_plural': 'Cotações de Mercado',
                'unique_together': {('commodity', 'date', 'source')},
            },
        ),
    ]
