# Generated by Django 4.2.29 on 2026-03-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(choices=[('SOY', 'Soja'), ('CRN', 'Milho'), ('WHT', 'Trigo')], default='SOY', max_length=3, verbose_name='Cultura')),
                ('date', models.DateField(verbose_name='Data da Cotação')),
                ('price_cents', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prêmio (Cents/Bushel)')),
                ('shipping_month', models.CharField(max_length=20, verbose_name='Mês de Embarque')),
                ('source', models.CharField(default='Notícias Agrícolas - Paranaguá', max_length=100, verbose_name='Fonte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prêmio de Exportação',
                'verbose_name_plural': 'Prêmios de Exportação',
                'unique_together': {('commodity', 'date', 'shipping_month')},
            },
        ),
    ]
