# Generated by Django 4.2.28 on 2026-02-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Data da Previsão')),
                ('max_temp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temp. Máxima (°C)')),
                ('min_temp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temp. Mínima (°C)')),
                ('precipitation', models.DecimalField(decimal_places=2, help_text='Acumulado de chuva no dia', max_digits=6, verbose_name='Chuva (mm)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
            ],
            options={
                'verbose_name': 'Previsão do Tempo',
                'verbose_name_plural': 'Previsões do Tempo',
                'ordering': ['date'],
            },
        ),
    ]
