# Generated by Django 4.2.28 on 2026-03-03 21:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Propriedade')),
                ('city', models.CharField(default='Toledo', max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(default='PR', max_length=2, verbose_name='UF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fazenda',
                'verbose_name_plural': 'Fazendas',
            },
        ),
        migrations.CreateModel(
            name='CropField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Talhão (ex: Sede Leste)')),
                ('commodity', models.CharField(choices=[('SOY', 'Soja'), ('CRN', 'Milho'), ('WHT', 'Trigo')], max_length=3, verbose_name='Cultura')),
                ('area_hectares', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Área (Hectares)')),
                ('planting_date', models.DateField(blank=True, null=True, verbose_name='Data de Plantio')),
                ('expected_yield_per_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Estimativa de Colheita (Sacas/ha)')),
                ('status', models.CharField(choices=[('PLANNED', 'Planejado'), ('PLANTED', 'Plantado'), ('HARVESTED', 'Colhido')], default='PLANNED', max_length=15, verbose_name='Status da Safra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='farms.farm', verbose_name='Fazenda')),
            ],
            options={
                'verbose_name': 'Talhão / Lavoura',
                'verbose_name_plural': 'Talhões / Lavouras',
            },
        ),
    ]
