# Generated by Django 4.2.29 on 2026-03-05 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriculturalInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('category', models.CharField(choices=[('SEED', 'Semente'), ('FERTILIZER', 'Fertilizante / Adubo'), ('PESTICIDE', 'Defensivo Químico'), ('FUEL', 'Combustível'), ('OTHER', 'Outro')], max_length=20, verbose_name='Categoria')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('unit', models.CharField(choices=[('KG', 'Quilogramas (kg)'), ('L', 'Litros (L)'), ('TON', 'Toneladas (ton)'), ('SC', 'Sacas'), ('UNIT', 'Unidade')], max_length=10, verbose_name='Unidade')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Custo Total (R$)')),
                ('purchase_date', models.DateField(verbose_name='Data da Compra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='farms.farm', verbose_name='Fazenda')),
            ],
            options={
                'verbose_name': 'Insumo Agrícola',
                'verbose_name_plural': 'Insumos Agrícolas',
            },
        ),
    ]
